---
sidebar: sidebar 
permalink: trident-rn.html 
keywords: 'what"s new, new features, enhancements, known issues, resolved issues, troubleshooting' 
summary: A NetApp está continuamente melhorando e aprimorando seus produtos e serviços. Aqui estão alguns dos mais recentes recursos, aprimoramentos e correções de bugs na versão mais recente do Astra Trident. 
---
= Notas de versão
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


As Notas de versão fornecem informações sobre novos recursos, aprimoramentos e correções de bugs na versão mais recente do Astra Trident.


WARNING: O `tridentctl` binário para Linux que é fornecido no arquivo zip do instalador é a versão testada e suportada. Esteja ciente de que o `macos` binário fornecido na `/extras` parte do arquivo zip não é testado ou suportado.



== O que há de novo

A NetApp está continuamente melhorando e aprimorando seus produtos e serviços. Aqui estão alguns dos mais recentes recursos e funcionalidades disponíveis com o Astra Trident.



=== Astra Trident 21.07.02

* Corrigido o problema em que clones de volumes XFS não podiam ser montados no mesmo nó que o volume de origem.




==== Melhorias

* Adicionado suporte para Kubernetes 1,22.
* Habilitou o operador do Trident e o gráfico de Helm para trabalhar com o Kubernetes 1,22.


Consulte https://github.com/NetApp/trident/releases["Astra Trident no GitHub"^] para obter mais informações.



=== Astra Trident 21.07.01

* Corrigido problema personalizado do instalador YAML com imagem diferente.
* Problema de cálculo do tamanho do instantâneo corrigido.


Consulte https://github.com/NetApp/trident/releases/tag/v21.07.1["Astra Trident no GitHub"^] para obter mais informações.



=== Astra Trident 21,07

O Astra Trident 21.07.0 está *não disponível para download*. Alterações introduzidas na `snapshotReserve` versão 21.07.0 podem resultar em CSI `VolumeSnapshots` inutilizável para criar PersistentVolumeClaim(s).

Se você já atualizou para a versão 21.07.0, é recomendável excluir o recém-criado `VolumeSnapshots` (provisionado com a versão 21.07.0) e fazer o downgrade para a versão anterior.

Consulte https://github.com/NetApp/trident/releases/tag/v21.07.0["Astra Trident no GitHub"^] para obter mais informações.



== Problemas conhecidos

Problemas conhecidos identificam problemas que podem impedi-lo de usar o produto com sucesso.

* Agora, o Astra Trident aplica um espaço em `fsType` (`fsType=""`branco ) para volumes que não têm o `fsType` especificado em seu StorageClass. Ao trabalhar com o Kubernetes 1,17 ou posterior, a Trident dá suporte a fornecer um espaço em branco `fsType` para volumes NFS. Para volumes iSCSI, é necessário definir o `fsType` no StorageClass ao aplicar um `fsGroup` contexto de uso de segurança.
* Ao usar um back-end em várias instâncias do Astra Trident, cada arquivo de configuração de back-end deve ter um valor diferente `storagePrefix` para backends do ONTAP ou usar um diferente `TenantName` para backends do SolidFire. O Astra Trident não consegue detectar volumes que outras instâncias do Astra Trident criaram. Tentar criar um volume existente em backends ONTAP ou SolidFire é bem-sucedido, porque o Astra Trident trata a criação de volume como uma operação idempotente. Se `storagePrefix` ou `TenantName` não forem diferentes, pode haver colisões de nomes para volumes criados no mesmo back-end.
* Ao instalar o Astra Trident (usando `tridentctl` ou o Operador Trident) e usar `tridentctl` para gerenciar o Astra Trident, você deve garantir que a `KUBECONFIG` variável de ambiente esteja definida. Isso é necessário para indicar o cluster do Kubernetes com `tridentctl` quem trabalhar. Ao trabalhar com vários ambientes do Kubernetes, você deve garantir que o `KUBECONFIG` arquivo seja obtido com precisão.
* Para executar a recuperação de espaço on-line para PVS iSCSI, o SO subjacente no nó de trabalho pode exigir que as opções de montagem sejam passadas para o volume. Isso é verdade para instâncias RHEL/RedHat CoreOS, que exigem o `discard` https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/managing_file_systems/discarding-unused-blocks_managing-file-systems["opção de montagem"^]; Certifique-se de que a opção Descartar mountOption está incluída no seu[`StorageClass`site para suportar descarte de blocos online.
* Se você tiver mais de uma instância do Astra Trident por cluster Kubernetes, o Astra Trident não poderá se comunicar com outras instâncias e não poderá descobrir outros volumes que eles criaram, o que leva a um comportamento inesperado e incorreto se mais de uma instância for executada em um cluster. Só deve haver uma instância do Astra Trident por cluster Kubernetes.
* Se os objetos baseados no Astra Trident `StorageClass` forem excluídos do Kubernetes enquanto o Astra Trident estiver off-line, o Astra Trident não removerá as classes de storage correspondentes de seu banco de dados quando ele voltar on-line. Você deve excluir essas classes de armazenamento usando `tridentctl` ou a API REST.
* Se um usuário excluir um PV provisionado pelo Astra Trident antes de excluir o PVC correspondente, o Astra Trident não excluirá automaticamente o volume de backup. Você deve remover o volume via `tridentctl` ou a API REST.
* A ONTAP não pode provisionar simultaneamente mais de um FlexGroup de cada vez, a menos que o conjunto de agregados seja exclusivo para cada solicitação de provisionamento.
* Ao usar o Astra Trident mais de IPv6 TB, você deve especificar `managementLIF` e `dataLIF` na definição de back-end entre colchetes. Por exemplo, ``[fd20:8b1e:b258:2000:f816:3eff:feec:0]``.
* Se estiver usando `solidfire-san` o driver com OpenShift 4,5, certifique-se de que os nós de trabalho subjacentes usem MD5 como o algoritmo de autenticação CHAP.




== Encontre mais informações

* https://github.com/NetApp/trident["Astra Trident no GitHub"^]
* https://netapp.io/persistent-storage-provisioner-for-kubernetes/["Blogs do Astra Trident"^]

